// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzgnionuvdjxvnpocytb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6Z25pb251dmRqeHZucG9jeXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDUwMjIsImV4cCI6MjA2MzE4MTAyMn0.rc37Nu7QOkprD6-1HELYSWL3IxXZ3ZrsVL7NaBd6iKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);